- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  connection: ssh
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
      become: yes

    # Uncomment and adjust the following tasks if needed
    #- name: Stop existing containers
    #  shell: docker stop $(docker ps -a -q)

    #- name: Delete all containers
    #  shell: docker rm $(docker ps -a -q)

    - name: Deploy Docker Container
      command: docker run -itd -p 8089:8081 lakshmikasi/insuranceproject1.1
